### ISSUE TITLE
POTENZIARE SERVER

### ISSUE THREAD

**Issue by ManuelDiGiacobbe** [ValentinaTibs/donatiles#50]

**Comment by ValentinaTibs** [comment]
Qual è il problema che vuoi mitigare?
Quale parte ti piacerebbe andasse più veloce?

**Comment by ManuelDiGiacobbe** [comment]
non riusciamo a capire quanto la lentezza sia data dalla nostra linea scandalosa sinceramente

**Comment by ValentinaTibs** [comment]
Setting up a bottleneck analysis
