### ISSUE TITLE
Quadrato grande negli effetti è ripetuto due volte, al posto di quadrato piccolo

### ISSUE THREAD

**Issue by ManuelDiGiacobbe** [ValentinaTibs/donatiles#51]

**Comment by ValentinaTibs** [comment]
Dove? Nei filtri? 
Hai controllato se i Tag relativi sono corretti?

**Comment by ManuelDiGiacobbe** [comment]
i tag sono corretti, è proprio un errore di dicitura, i vari tag sono divisi bene tra quadrato grande e piccolo

**Comment by ValentinaTibs** [comment]
hai incasinato i tag
![image](https://user-images.githubusercontent.com/18550002/97577244-75d98580-19ef-11eb-997e-1beaabe8123a.png)
Non farlo più

**Comment by ManuelDiGiacobbe** [comment]
Scusa

Il gio 29 ott 2020, 14:03 ValentinaTibs <notifications@github.com> ha
scritto:
