### ISSUE TITLE
la serie TW presentava il nel backend il formato 25x150 mentre da sito si vedeva 25x120 (tag inserito per sbaglio perchè il formato non esiste)

### ISSUE THREAD

**Issue by ManuelDiGiacobbe** [ValentinaTibs/donatiles#52]
ho cancellato il tag 25x120 e adesso se provo ad entrare dal back nella TW mi da errore

Request Method: | GET
-- | --
https://nameless-cove-70266.herokuapp.com/admin/taleoftiles/product/7/change/?_changelist_filters=q%3Dtw
3.1.1
AttributeError
'NoneType' object has no attribute 'name'
/app/taleoftiles/models.py, line 259, in __str__
/app/.heroku/python/bin/python
3.7.4
['/app/.heroku/python/bin',  '/app',  '/app/.heroku/python/lib/python37.zip',  '/app/.heroku/python/lib/python3.7',  '/app/.heroku/python/lib/python3.7/lib-dynload',  '/app/.heroku/python/lib/python3.7/site-packages']
Wed, 28 Oct 2020 08:58:49 +0000

**Comment by ValentinaTibs** [comment]
dovrei averlo risolto - @ManuelDiGiacobbe  mi confermi?
