### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by ValentinaTibs** [ValentinaTibs/donatiles#8]
http://www.taleoftiles.it/en/product/TU17

**Comment by ValentinaTibs** [comment]
@ManuelDiGiacobbe ci sono dei prodotti che non hanno serie - 
manca anche a TU09
e mancano anche di effetto

**Comment by ManuelDiGiacobbe** [comment]
TU è cotto etrusco, che come abbiamo detto sono da cancellare tutti e reinserire con i vari effetti
